id: a3237f6764ba4d7d9ca6c7e091a11f1c
initial_creation_type: ocr
source_metadata:
  volumes:
    dea246cd3c444fefa23ceed9f2f69082:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: རྟེན་ཅིང་འབྲེལ་པར་འབྱུང་བའི་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1605
      volume_number: 57
